### ISSUE TITLE
Cmake Install

### ISSUE THREAD

**Issue by Hoikas** [H-uru/PlasmaShop#43]
PlasmaShop installs directly into the `CMAKE_INSTALL_PREFIX` instead of the the `bin` subdirectory thereof.

**Comment by zrax** [comment]
Only on Windows and OSX (which should be a bundle rather than a Unix-style tree).  On *nix, it installs the binaries to `${CMAKE_INSTALL_PREFIX}/bin`.

**Comment by Hoikas** [comment]
libHSPlasma installs into the bin subdirectory on Windows, so to make a functioning PlasmaShop tree, I have to make install libHSPlasma, make install PlasmaShop, then copy the PlasmaShop exes or libHSPlasma libraries into the appropriate location. It's the last step that I take issue with. Considering that libHSPlasma has binary libs and includes, it seemed reasonable to me to expect that PlasmaShop should be installing into the `bin` subdirectory.
