### ISSUE TITLE
Cannot open Python.0.elf log file: Invalid UTF-8 sequence byte

### ISSUE THREAD

**Issue by diafero** [H-uru/PlasmaShop#58]
I am trying to debug an age crash, but unfortunately I cannot even open the log files generated by Uru -- PlasmaShop just crashes. When I open it in the terminal, I see an error printed to stderr:
```
terminate called after throwing an instance of 'ST::unicode_error'
  what():  Invalid UTF-8 sequence byte
Aborted (core dumped)
```
Uru itself is fine with non-UTF-8 strings appearing in various places (and at least PyPRP ages created by German age builders frequently use non-UTF-8 names for Uru game objects), so PlasmaShop should also be able to cope with this.

**Comment by Hoikas** [comment]
More windows-1252 probably 😢
